name: 'Run Runbook in Octopus Deploy'
description: 'GitHub Action to run a runbook in Octopus Deploy'
author: 'Octopus Deploy'
branding:
  color: 'blue'
  icon: 'book'

inputs:
  project:
    description: 'The name or ID of the project associated with this runbook.'
    required: true
  runbook:
    description: 'The name or ID of the runbook. If the name is supplied, the project input value must also be specified.'
    required: true
  environments:
    description: 'A comma-delimited list of environments in Octopus Deploy in which to run (i.e. "Dev,Test,Prod").'
    required: true
  variables:
    description: 'A list of prompted variables in the format, Label:Value. For JSON values, embedded quotation marks should be escaped with a backslash. Supports multiple prompted variables; one per line.'
  api_key:
    description: 'The API key used to access Octopus Deploy. An API key is required, but you may also use the OCTOPUS_API_KEY environment variable. If the guest account is enabled, a key of API-GUEST may be used. It is strongly recommended to retrieve this value from a GitHub secret.'
  proxy:
    description: 'The URL of a proxy to use (i.e. https://proxy.example.com).'
  proxy_password:
    description: 'The password used to connect to a proxy. It is strongly recommended to retrieve this value from a GitHub secret. If proxy_username and proxy_password are omitted and proxy URL is specified, the default credentials are used.'
  proxy_username:
    description: 'The username used to connect to a proxy. It is strongly recommended to retrieve this value from a GitHub secret.'
  server:
    description: 'The base URL hosting Octopus Deploy (i.e. "https://octopus.example.com/"). The Server URL is required, but you may also use the OCTOPUS_HOST environment variable.'
  space:
    description: 'The name or ID of a space within which this command will be executed. If omitted, the default space will be used.'

runs:
  using: 'node12'
  main: 'dist/index.js'
